ARG VERSION=latest
FROM zookeeper:latest
RUN echo $VERSION > image_version

# Add metadata...
LABEL maintainer="Andrea Graziani"
LABEL version="1.0"
LABEL description="SDDC A.A. 2018-2019"

COPY ./zoo.cfg /conf/zoo.cfg
RUN zkServer.sh start

# ./bin/zkCli.sh 127.0.0.1:2181
